name = "bidform-online"
compatibility_date = "2024-09-10"

[env.production]
name = "bidform-online"

# Cloudflare Pages configuration
# Build command: npm run build
# Build output directory: dist
# Root directory: (leave empty)